### ISSUE TITLE
Migrate HLS reconciliation EC2 instance to the new CSET instance on MCP

### ISSUE THREAD

**Issue by madhuksridhar** [NASA-IMPACT/hls-project#2]
## Background

This EC2 instance is used to manage/deploy LPDAAC reconciliation workflow.  We need to migrate this to a new CSET instance on MCP and remove the old EC2 instance.
 
Old instance name: HLS_reconciliation
New instance name: HLS_reconciliation_CSET_2023
LPDAAC Reconciliation repo: [hls-lpdaac-orchestration](https://github.com/NASA-IMPACT/hls-lpdaac-orchestration)

## Tasks

- [x] Set up the new instance with all dependencies
- [ ] Try to connect to the deployed Pulumi stack form the new instance. 
- [ ] After successfully linking the Pulumi stack, test and ensure that the daily reconciliation procedure remains unaffected and continues to send notification reports
- [ ] Inform CMT about successful migration

**Comment by chuckwondo** [comment]
I am unable to connect via ssh. My attempt to connect times out, but I suspect that's because my ip address isn't in the allowed ranges that I see configured for inbound on port 22. I suspect these are MCP ranges:

- 35.161.197.194/32
- 207.157.81.66/32

Connecting to the VPN didn't help. However, I was able to connect via Session Manager in the browser (via AWS Console).

**Comment by madhuksridhar** [comment]
Compiled some notes about connecting to Pulumi stack [here](https://docs.google.com/document/d/1_HmPROH5BCCxu0P8a9jugc7hkMSZrosJRpDtFjlwgok/edit?usp=drive_link). Need to tagup with @chuckwondo to discuss further.
