### ISSUE TITLE
Operational Readiness Review Checklist (tracking tasks/tickets)

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/hls-project#30]
### Description
The ORR for HLS-VI still requires several tasks to be completed. This ticket is to track all the existing tickets related to the ORR. 

### Acceptance Criteria: 
- [ ] [HLS VI: Add CMR STAC generation capabilities](https://github.com/NASA-IMPACT/hls-project/issues/13)
- [ ] [HLS-VI: Create HLS VI User Guide](https://github.com/NASA-IMPACT/hls-project/issues/8)
- [ ] [HLS-VI: Scientific Evaluation](https://github.com/NASA-IMPACT/hls_development/issues/228)
- [ ] [HLS-VI: Integration and unit tests](https://github.com/orgs/NASA-IMPACT/projects/23/views/1#:~:text=%23-,219,-chuckwondo)
- [ ] [HLS-VI test failures and anomalies](https://github.com/NASA-IMPACT/hls-project/issues/29)
- [ ] [HLS-VI Operational Readiness Review presentation](https://github.com/NASA-IMPACT/hls-project/issues/28)
- [ ] [HLS-VI programmatic products needed for ORR review](https://github.com/NASA-IMPACT/hls-project/issues/26)
- [ ] [Draft a preliminary HLS-VI transition plan](https://github.com/NASA-IMPACT/hls-project/issues/25)
- [ ] [Update/complete all ORR technical documentation](https://github.com/NASA-IMPACT/hls-project/issues/24)
- [ ] [Obtain HLS-VI DOI and landing page](https://github.com/NASA-IMPACT/hls-project/issues/23)
- [ ] [Create a HLS-VI operational contingency plan](https://github.com/NASA-IMPACT/hls-project/issues/22)
- [ ] [HLS-VI products to be delivered to LPDAAC](https://github.com/NASA-IMPACT/hls_development/issues/279)
- [ ] [HLS-VI data/metadata sent to LPDAAC using CNM transfer scheme](https://github.com/NASA-IMPACT/hls-project/issues/21)
- [ ] [Send HLS-VI daily reports to LPDAAC](https://github.com/NASA-IMPACT/hls_development/issues/278)
- [ ] [HLS-VI: Test capability to send data to LPDAAC UAT](https://github.com/NASA-IMPACT/hls-project/issues/11)
- [ ] [HLS-VI New reconciliation workflow](https://github.com/orgs/NASA-IMPACT/projects/23/views/1?pane=issue&itemId=50332371#:~:text=%23-,223,-Tracked%20by%202)
