### ISSUE TITLE
Historical verification of GIBS WV

### ISSUE THREAD

**Issue by trangthuyvo0109** [NASA-IMPACT/hls-project#41]
Historical processing of HLS S30 data between 2015 - 2022 was completed in 2023. However, a verification of HLS S30 granules was not performed. Using the availability of  [S2 inventory files](https://csv.dataspace.copernicus.eu/) on ESA’s Copernicus Dataspace for S2A and S2B, we compare S30 CMR inventory with ESA’s inventory. 

```[tasklist]
### Tasks
- [x] Downloading images from S3 bucket
- [x] Conducting the verification from 2017 - 2020 and update to the [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1LADBcTUyyar3pyywoM8aTbOG-WKj0AZ2_dG_LUwRNUo/edit?gid=329128048#gid=329128048)
- [x] Articulate some findings from the verification in [this slide](https://docs.google.com/presentation/d/1cVQ4daXfgl3uexqiCIl4XJKJLTnNDYq2rJWbafXK59I/edit#slide=id.g308701b2e6e_0_7) for reference
```

**Comment by madhuksridhar** [comment]
@trangthuyvo0109 can this be closed?

**Comment by trangthuyvo0109** [comment]
Without further investigations, I think it should be good to close!
