### ISSUE TITLE
HLS VI: Communication and Advertisement

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/hls-project#9]
## Description

The HLS VI product needs to be communicated and advertised in coordination with LPDAAC and SNWG. 

[Draft](https://docs.google.com/document/d/1I-mn0eOPdWC3ib25nFOAt0MbI6D8sbrzvFHuVRuesK4/edit)

- [x] Coordinate VI product with LPDAAC and SNWG
- [ ] Provide LPDAAC a short description for an advertisement via their website
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/hls_development/issues/307
- [ ] https://github.com/NASA-IMPACT/hls_development/issues/308
```

**Comment by Jeaton1021** [comment]
@ashleyriddle92 - might need support for this ticket. Will touch base soon.

**Comment by madhuksridhar** [comment]
We received a request from LP and ESDIS for more information about HLS-VI. 
The questions and responses can be accessed here: https://docs.google.com/document/d/1mUhPZmMpDuXohvesD4taM70O-qzWuo0Pl6JrmW3lU0o/edit
CC @bwbaker1

**Comment by madhuksridhar** [comment]
Draft of LPDAAC announcement reviewed by Junchang:
https://docs.google.com/document/d/1I-mn0eOPdWC3ib25nFOAt0MbI6D8sbrzvFHuVRuesK4/edit?tab=t.0

@bwbaker1 was this sent to LPDAAC? If so we can probably close this ticket
